name: Production - e2e
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 */4 * * *"

jobs:
  basicTests:
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]

    name: "Playwright tests"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:latest
    steps:
      - name: Random workflow stop (50% chance)
        run: |
          if [ $(( $RANDOM % 2 )) -eq 0 ]; then
            echo "Randomly stopping workflow (50% probability)"
            exit 1
          fi
          echo "Continuing workflow execution"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # https://github.com/actions/runner-images/issues/6775
      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install

      - name: Run docs e2e tests
        continue-on-error: true
        env:
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          node scripts/fake-git-data/fake-git-data.js
          npx pwc --shard=${{ matrix.shard }}/${{ strategy.job-total }} --ci-build-id "docs-${{ github.run_id }}-${{ github.run_attempt }}" --project docs

      - name: Random workflow stop (10% chance)
        run: |
          if [ $(( $RANDOM % 10 )) -eq 0 ]; then
            echo "Randomly stopping workflow (10% probability)"
            exit 1
          fi
          echo "Continuing workflow execution"

      - name: Run landing-page e2e tests
        continue-on-error: true
        env:
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          node scripts/fake-git-data/fake-git-data.js
          npx pwc --shard=${{ matrix.shard }}/${{ strategy.job-total }} --ci-build-id "landing-${{ github.run_id }}-${{ github.run_attempt }}" --project landing-page

      - name: Random workflow stop (10% chance)
        run: |
          if [ $(( $RANDOM % 10 )) -eq 0 ]; then
            echo "Randomly stopping workflow (10% probability)"
            exit 1
          fi
          echo "Continuing workflow execution"

      - name: Run web-app e2e tests
        continue-on-error: true
        env:
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        run: |
          node scripts/fake-git-data/fake-git-data.js
          npx pwc --shard=${{ matrix.shard }}/${{ strategy.job-total }} --ci-build-id "web-${{ github.run_id }}-${{ github.run_attempt }}" --project web-app
